name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up libraries
        run: |
          npm ci --prefix react

      - name: Run Tests
        working-directory: tests
        run: |
          npm ci
          npx playwright install --with-deps
          npm playwright test