name: Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: |
                  bun install --cwd base
                  bun install --cwd react
                  bun install --cwd svelte
                  bun install --cwd vue

            - name: Base tests
              run: |
                  cd base
                  bun test
                  bun run ts-validate

            - name: Svelte tests
              run: |
                  cd svelte
                  bun run test
                  bun run check

            - name: React tests
              run: |
                  cd react  
                  bun run build:prop-keys
                  bun run test
                  bun run ts-validate

            - name: Vue tests
              run: |
                  cd vue
                  bun run test
                  bun run ts-validate
