name: Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v2

            - name: Set up libraries
              run: |
                  bun install --cwd base
                  bun install --cwd react
                  bun install --cwd svelte
                  bun install --cwd vue

            - name: Run base tests
              run: |
                  cd base
                  bun test
                  bun run ts-validate

            - name: Run svelte tests
              run: |
                  cd svelte
                  bun run test
                  bun run check

            - name: Run react tests
              run: |
                  cd react
                  bun run test
                  bun run ts-validate

            - name: Run vue tests
              run: |
                  cd vue
                  bun run test
                  bun run ts-validate
